services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    restart: always
    tty: true
    environment:
      MYSQL_DATABASE: 'app'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: